[workspace]
members = [
    "ramhorns-ext",
    "ramhorns-derive-ext",
    "tests",
]

[patch.crates-io]
ramhorns-derive-ext = { path = "./ramhorns-derive-ext" }

[profile.bench]
lto = "fat"
codegen-units = 1
